server:
  port: 9090


app:
  eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring:
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
    url: jdbc:mysql://localhost:3306/produto?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

---
spring:
  profiles:
    - docker
server:
  port: 8080

app:
  eureka-server: eureka