server:
  port: 9090

app:
  eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring:
  cloud:
    stream:
      binders:
        kafka:
          type: kafka
      bindings:
        output-produto:
          binder: kafka
          destination: topic-produto
          group-id: '${spring.application.name}'
          producer:
            partition-count: 16
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          health-timeout: 30
          auto-create-topics: true
          auto-add-partitions: true
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
    url: jdbc:mysql://localhost:3306/produto?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

feign:
  hystrix:
    enabled: enable
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: FULL
        loggerLevel: FULL

logging:
  level:
    org.springframework: DEBUG

inventario:
  url: http://localhost:9091

---
spring:
  profiles:
    - docker
server:
  port: 8080

app:
  eureka-server: eureka

inventario:
  url: http://inventario/
